server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    include-message: always

spring:
  thymeleaf:
    cache: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/activemq?useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jms:
    pub-sub-domain: true

MainTopic: chatroom


