server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    include-message: always

spring:
  thymeleaf:
    cache: false
  datasource:
    password: Huangzhuo2000
    url: jdbc:mysql://111.230.187.245:29733/dynamicweb?useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis:
  configuration:
    map-underscore-to-camel-case:  true
